### ISSUE TITLE
Table header obscuring dropdown in Bootstrap on IE8

### ISSUE THREAD

**Issue by abeverley** [mkoryak/floatThead#144]
I've come across a strange problem when using floatThead with IE8 and Bootstrap. When the page first loads, the floated table header will obscure any subsequently displayed Bootstrap dropdowns, as per the screenshot below. However, as soon as the table is scrolled, the dropdown is then displayed correctly on top.

This appears to be something to do with the z-index, so I set that option to 999 instead of 1001 (the dropdown is configured as 1000). However, what I don't understand is:
1. Why it only affects IE8
2. Setting the option as 1001 (the default) also fixes the problem

I'm happy that I have a workaround, but given the time I've spent on this I thought it worth documenting for others. Is this an IE8 bug or is there something else going on?

Thanks for a great plugin,

Andy

![screenshot from 2014-12-16 09 38 19](https://cloud.githubusercontent.com/assets/4589486/5451482/688f58dc-8508-11e4-9e02-65bcc581e810.png)

**Comment by abeverley** [comment]
Fair enough! Like you say, it's at least documented here if someone else has the same problem. Thanks.

**Comment by foool** [comment]
@mkoryak I find a similar problem and the floatThead covers the upper dropdown menu:
https://jsfiddle.net/foool/zumyz9aL/2/
I am not sure this is a bug or I miss to set the CSS.

**Comment by mkoryak** [comment]
In ie8 ?!

Please make a new issue. It's easy to lose track of old closed issues for
me.



On Oct 21, 2017 11:24 AM, "Qing" <notifications@github.com> wrote:

@mkoryak <https://github.com/mkoryak> I find a similar problem and the
floatThead covers the upper dropdown menu:
https://jsfiddle.net/foool/zumyz9aL/2/
I am not sure this is a bug or I miss to set the CSS.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mkoryak/floatThead/issues/144#issuecomment-338410012>,
or mute the thread

**Comment by mkoryak** [comment]
nevermind. I fixed it on my phone!

https://jsfiddle.net/zumyz9aL/3/
