### ISSUE TITLE
screenreader support

### ISSUE THREAD

**Issue by scriby** [mkoryak/floatThead#146]
I think a couple minor changes need to be made to allow screen readers to work with tables that are using floatThead:

* Mark the floated table with `aria-hidden="true"` so it's ignored
* Keep the contents of the original headers in place such that the screen reader can find and read them.

**Comment by mkoryak** [comment]
Aria support is going to require an  option to turn it on, and be off by default - unfortunately. 

see this test case:
http://mkoryak.github.io/floatThead/tests/issue-56/

the text of the cloned header gets a giant font because of existing css. I am not going to even attempt to reset the css on those elements because mucking with css usually ends badly. 

Ill have to introduce an option to enable it :p 
Ill still include the aria-* attributes though, those dont hurt.

**Comment by mkoryak** [comment]
in the latest version `enableAria` is a boolean option that needs to be set to true in order to have screen reader support

**Comment by scriby** [comment]
great, thanks!
