### ISSUE TITLE
Using floatThead from an angular application using only jqLite - possible?

### ISSUE THREAD

**Issue by jurko-gospodnetic** [mkoryak/floatThead#174]
Hi. This is just a question and not a real bug report issue. :-)

I have not yet taken the time to try this out myself, and though to ask here first - anyone had any luck getting this component to work with jqLite, as provided by angular? That is, without full jQuery support.

Asking because I'm looking for ideas on how to get the 'sticky header' feature in an existing angular app, and since it is not already using jQuery, I'm curious as to whether this component can be used without forcing a new Query dependency as well.

Many thanks.

Best regards,
  Jurko Gospodnetić

**Comment by mkoryak** [comment]
it will not work out of the box with jqLite because jqLite does not support selectors. We could try to convert the code to use `querySelectorAll` but that would mean dropping ie8 support - which might not be a bad thing

**Comment by mkoryak** [comment]
looking into this more - conversion will not be as straightforward as replacing all selectors with querySelectorAll. There is much more stuff missing from jqLite:
https://docs.angularjs.org/api/ng/function/angular.element

**Comment by mkoryak** [comment]
I would be interested in trying to put out a new version that only depends on jqlite. I think the approach id like to take would be to detect if `window.angular.element` is present and instead of passing in `jQuery` into the script - pass a new function that uses jqLite under the hood for all the functionality it provides but also uses `document.querySelectorAll` and a few other methods we will have to write ourselves such as `.each` and `.filter` etc  - ill get a list of all the methods ill need to implement. 

The idea is that if you want to use the script with jqlite, you would use a version that includes this shim - just like I do now with the lite version that doesnt include the underscore shim. 

This could make for an interesting side project - a jqLite to jquery shim generator where you pick the methods from jquery that you need and it generates a shim for you.

**Comment by mkoryak** [comment]
It turns out that there is more work here then I first imagined, and I don't have time to do it "right". Maybe some day.

**Comment by jurko-gospodnetic** [comment]
I've added it to may 'things to look at' todo list. So I'll get back to you when I have something. Thanks for all you work so far though! :-)

**Comment by mkoryak** [comment]
Well, if you do end up doing it, please try to do it so that the changes to the plugin are minimized. I would be ok replacing `$(n).filter(m)` with `X.filter(n, m)` though ideally it would be even better if no changes were necessary (other than knowing that I couldnt use any new jquery methods). The shim methods would go into another file that would be optional for people not using jquery. 

Good luck!
