### ISSUE TITLE
Header height shrinks and is positions top-left of screen.

### ISSUE THREAD

**Issue by abdulrahmanosoble** [mkoryak/floatThead#218]
When floatThead kicks in (imean when you scroll down), my header height shrinks not completely displaying the <td> cells and is moved from the center of the screen to the left. Here is a JSFiddle showing the problem: http://jsfiddle.net/m3omd6wL/2/

**Comment by abdulrahmanosoble** [comment]
After much debugging I've found that the <div class="floatThead-floatContainer floatThead-container">
for whatever reason has it's height set to 16px. The normal height of my header is 30px.

**Comment by abdulrahmanosoble** [comment]
So a temporary band-aid fix for me was to add "height: '30px', " to  "$floatContainer.css({". I'm still very unsure of why this happened in the first place and I probably won't be able to use this since I need my page to be responsive.

**Comment by mkoryak** [comment]
it looks like you specify heights of things mostly in percentages. when the header is floated it is moved into another table who's height is equal to the the height of the original header. because your styles continue apply to it in it's new location, the percentage heights no longer make sense. Unfortunately there is nothing I can do to fix this.

**Comment by abdulrahmanosoble** [comment]
I managed to fix it with a small band aid fix. I set the float-container class height to 200% and applied a left margin of 1% to it. I did this in the jquery. 

I might just replace the margin fix with the proper fix you have me.

Thanks alot for looking at it.
