### ISSUE TITLE
IE, Firefox, Chrome overflow scrolling - header alignment issue caused by margin

### ISSUE THREAD

**Issue by carolynpearce** [mkoryak/floatThead#223]
Hello!

I am seeing an issue on my page using overflow scrolling, both of which occur once the headers are floating (i.e., you have scrolled down). As you scroll horizontally, the header is aligned with the table but does not cover the complete width of the table, and once you have scrolled horizontally as far as you can, the header becomes misaligned.

I believe that these two issues are caused by an element between the container and the table that has a margin greater than 0.

Here is a jsfiddle showing the issue: https://jsfiddle.net/o4ckgnh3/1/

I have looked through your documentation (particularly about ideal HTML) and past closed issues, but I can't seem to find an explanation for why this happening. I apologize in advance if you have already addressed this in a previous issue or anywhere on your sight!

If you can help me solve this issue or at least explain why this can't be supported, that would be very much appreciated!

Additional information that might help-- 1) overflow scrolling has to be used because this content is within a pane, 2) there are multiple header rows, and 3) setting useAbsolutePositioning to true completely messes up the header rows in terms of position and style (not easily demonstrated in fiddle)

Chrome: Version 43.0.2357.132
IE: 11
Firefox: 39

jQuery.floatThead: 1.2.12
jQuery: 2.0.2

Thank you for any help you can give!

**Comment by mkoryak** [comment]
Hi,
here is an update fiddle that works better: https://jsfiddle.net/o4ckgnh3/2/ - your first row in the header was invalid html because it didnt contain the same number of columns as your table. 

changing to useAbsolute fixes the other problem. 

The reason that it is acting buggy is that this plugin expects that the scrolling container be a parent of the table (though its ok if there is stuff above and below the table, but not on the sides between it and the container) you have stuff on the sides. 
Its really hard to calculate where the table header is to position the floating header over it in the layout mode that is broken, so thats why I make some assumptions about the scrolling container.

**Comment by carolynpearce** [comment]
Okay, thanks for your response! The problem I'm still seeing with useAbsolute is that the header no longer respects the margin. The page I'm working with is a bit outdated, so I expect some things to be buggy! Thanks for the explanation.

**Comment by mkoryak** [comment]
If possible, if you put the scrolling container as the direct parent of the table, everything will work much better. You might be able to do that and restyle some other stuff instead of trying to fight the plugin
