### ISSUE TITLE
Using floatThead with StupidTable sorting

### ISSUE THREAD

**Issue by MrNickWard** [mkoryak/floatThead#225]
Hi

I am trying to integrate floatThead with Stupid Tables but sorting is not working when the floating header is clicked. This seems similar to this issue https://github.com/mkoryak/floatThead/issues/37/ that uses a different sorting plugin.

Please see the following example https://jsfiddle.net/qesyxarv/13/ 

PS my cat is called Joey and he is the best cat in the world... apart from 5am every morning when he wakes me up for breakfast!

Thanks

Nick

**Comment by mkoryak** [comment]
Nick, 
Its a lost cause. It wont work with it without a major rewrite. The stupid plugin does a lot things like this:

bind an event to an element in the table, on event, find the closest table and then search down from the table to find things within table. This wont work since my plugin splits the table into 2 tables. It would work if the stupid table plugin cached all the selectors it needed upon startup. It doesnt even have to cache them all, just the thead and tbody, and then use those 2 elements for finding subsequent elements it needs.

**Comment by MrNickWard** [comment]
Thanks for the very speedy response!

Shame as my testing showed that this is the fastest sorting plugin for
large tables (eg 1000 rows and 50 columns). I tried jquery.tablesort.js
with your suggested modifications and this was much slower and did some
strange sort ordering. Have settled on jquery.tablesorter.js and this is
not quite as fast as StupidTables but works with no modifications.

Thanks

Nick

**Comment by mkoryak** [comment]
I am not saying that it isn't possible to fix it. You can do it and PR it into there, but it wont be trivial because of their architecture. Here is a starting point if you want: https://jsfiddle.net/qesyxarv/15/ 
I made some changes to start supporting the plugin but gave up because it was taking too long.

**Comment by mkoryak** [comment]
let me know if you end up doing anything with this

**Comment by MrNickWard** [comment]
Thanks

Currently tweaking my C# table writer so I can do some more benchmarking and will let you know early next week.
