### ISSUE TITLE
Keep captions fixed?

### ISSUE THREAD

**Issue by killersdeat0** [mkoryak/floatThead#227]
Hey! First of all, thanks a lot for all of your work. The floatThead works really well (and is almost fool-proof for a fool like me). Almost. I have a table that I am keeping floated to allow for scrolling inside a small div. I have a table name as a caption that I wanted to keep floated along with the table. I probably could fix this through css and have a div outside instead but since I'm new to CSS (mostly back-end programmer) I can't figure out how to keep a div above a table. 

So is there a way of somehow keeping the captions fixed along with the thead? 

Attached are pictures of my problem,

![screen shot 2015-08-04 at 10 16 44 am](https://cloud.githubusercontent.com/assets/12938561/9064498/70847168-3a92-11e5-82bc-fb2a89ddd0c9.png)
![screen shot 2015-08-04 at 10 16 14 am](https://cloud.githubusercontent.com/assets/12938561/9064507/77fae79c-3a92-11e5-990d-6f442c87316d.png)

(I want the Neighbors Enriched GO Terms(FDR<0.05) to stay while scrolling).

**Comment by mkoryak** [comment]
You can do this by moving the caption outside of the scrolling container for the table, right?

another hacky way, would be to put the caption inside of the thead like so:

```html
<thead>
<tr>
<th class="special" colspan="7">Neighbors Enriched GO Terms(FDR<0.05)</th>
</tr>
... rest of your thead goes here
```

if you take that path, you will need to style the special cell so that it appears to not be part of the table, and change the  `headerCellSelector` option to `headerCellSelector: 'tr:last>th:visible'`

**Comment by killersdeat0** [comment]
I would move it outside the div but there's a bunch of css issues that comes with it(the site's a mess haha). But the hacky way worked perfectly. Thanks a lot!
