### ISSUE TITLE
tfoot obscured by thead in IE11 when grid has no rows

### ISSUE THREAD

**Issue by andy-thomas** [mkoryak/floatThead#282]
Hi Misha,

I am using your floatThead javascript file in a project that I am working on, and for the most part, it is working well. However, the is one scenario where I am having a problem. The grid has thead, tbody and tfoot element. The scenario is when the grid is displayed in Internet Explorer 11 with no rows. In this case, the stuff in the tfoot element is obscured behind the thead stuff. 

(I’m sorry, but I cannot copy it to jsFiddle, since it is quite complex, involving knockout binding, dynamic adding of columns, etc. I will try to explain with code snippets and screenshots- see attached document.)

[floatThead question.docx](https://github.com/mkoryak/floatThead/files/92607/floatThead.question.docx)
The issue appears to be that the plug-in generates a container div around the thead, which has an in-line style of “position: fixed”. this seems to be causing the tfoot element to sit behind it, i.e. obscured by it

**Comment by mkoryak** [comment]
sorry, I cant read docx files unless you pay me. can you put it on the web somewhere?

**Comment by andy-thomas** [comment]
Here is a jsFiddle sample: https://jsfiddle.net/AndyThomas/2xLbzk3n/
Try it in both IE and Chrome - in Chrome you can see both. In IE, the footer is obscured unless the rows are uncommented out

**Comment by mkoryak** [comment]
Great, thanks! 
Ill fire up the vm and take a look

**Comment by rcloutier** [comment]
This issue happens with any row, not just the footer. If you uncomment the tbody rows in Andy's fiddle above, you will see that the first row is also covered by the header. I have verified that this occurs in IE-11, but not in Firefox, Chrome, or Edge.

**Comment by rcloutier** [comment]
It looks to me as though, in IE-11, the original thead is not being retained in the scrolling table. In other browsers, the thead is in the overlay table AND in the scroll table, to space the tbody cells down.

**Comment by mkoryak** [comment]
yeah, there should be a dummy thead that is of the height of the original. its not appearing in ie11, probably a regression in one of the last few versions.

**Comment by rcloutier** [comment]
1.3.3dev still doesn't work in IE11 (11.0.9600.17959).

**Comment by mkoryak** [comment]
you are right, this fix didnt work. my test was not very good

**Comment by andy-thomas** [comment]
Question - Why would it matter about what the contents of the tfoot element are? In particular, why should the number cells cause the jsfiddle sample to break?

**Comment by rcloutier** [comment]
I don't know the exact mechanism because I have not studied the code, but the plugin does not like it if the number of header cells don't match the number of body cells (and presumably the footer cells too.)

Your fiddle had 8 header cells and 9 body and footer cells. Adding a 9th header cell made 2 things happen: 1) the first row was no longer hidden, and 2) the sticky header cell widths matched the widths of the rest of the table. 

The reason it fails with an unequal number of cells is because the dummy header that is created in the scrolling part of the table does not get created in IE-11, but it does get created in other browsers. This dummy header correctly spaces the column widths as it would if the table were in its original form, plus it adds a buffer to space the first row down enough so that it is not masked by the fixed header.

**Comment by mkoryak** [comment]
correct, the plugin expects that the numbers of cells in the body match that of the header. this is required because it must set the width of each header cell to be the same as the width of the corresponding cell in the body. 

there is no reason why you would need to have unequal number of cells in your table's body than that of the header. you should set the colspan of a column adjacent to the missing column to be 2 so that the number of columns remains equal. 

@rcloutier is probably right about ie11, that it does not let you insert a row with number of cells that is not the same as the number of columns in your table, if you do it programmatically. it might also require that a colgroup be present.

**Comment by andy-thomas** [comment]
I have updated the JsFiddle sample (https://jsfiddle.net/AndyThomas/2xLbzk3n/), so that the number of cells match, but where the tfoot has cells with colspan>1.
It appears to work in IE better if we include a getSizingRow option, even where no row exists.

**Comment by mkoryak** [comment]
`getSizingRow` is required in ie if your first row in tbody ever has an colspans. This is in the docs.
