### ISSUE TITLE
In IE, header widths are incorrect if first row has element which spans two columns

### ISSUE THREAD

**Issue by andy-thomas** [mkoryak/floatThead#283]
See https://jsfiddle.net/AndyThomas/j2o7sspq/. It looks good in Chrome. However, in IE, if you inspect the generated <colgroup> element, the styles for each <col> element have lost their width information. 

In Chrome: < col style="width: 75px;" >.    In IE: < col ></ col >  

This only happens in IE, if the first row has cells which span columns.
The documentation says that the plug-in will not work if "Your table has invalid markup, such as unmatched number of columns in tbody and thead". 
In this case, there is a mismatch between the number of headers and the number of cells (by design - the grid needs to display data in a hierarchical manner). However the markup is not invalid in any other sense (e.g. malformed HTML).

**Comment by mkoryak** [comment]
i should update the docs to include tfoot in that statement, your tfood contains 9 columns while the rest of the table contains 8. 

also for ie you will require `getSizingRow` option because your first row contains  cells with colspans (see docs about that option for more info)
here is what I think the working code should look like (didnt test in ie)

https://jsfiddle.net/j2o7sspq/7/

**Comment by andy-thomas** [comment]
That JsFiddle example works in IE11. Getting the last row is a good approach in the scenario where the grid displays hierarchical data. Thanks.

getSizingRow: function($table){return $table.find('tbody tr:visible:last>*')

**Comment by mkoryak** [comment]
so is this solved now?
