### ISSUE TITLE
Trouble displaying table in IE11 with thead contains colspan

### ISSUE THREAD

**Issue by smaouad** [mkoryak/floatThead#286]
Hi, 
Im kind of newbie in github, i'll try to explain my problem.
I used your pluggin to float the thead of my table, it works just fine in Firefox and Chrome but not for IE11. I created a JSFiddle for the matter 
[https://jsfiddle.net/1864hmx4/4/](url)
My header table is complex. I generate dynamically the header.
the first column is empty, i used it just for showing or not a information picture that's why the first th has a colspan = 2.
On the tbody, rows are grouped so we have sometimes tr with colspan = totalcolumns
My problem is that the table displays perfectly in firefox but not in IE11. Maybe i didn't understand  how to setup the getSizingRow option. I would like to have the same render like in firefox.

Can you help me please ?

**Comment by mkoryak** [comment]
`getSizingRow` must return a selector which will contain a list of table cell nodes (either td or th) where the number of nodes is equal to the number of columns in your table. If your table looked like this: 
```html
<table><thead>....</thead><tbody>
<tr><td colspan='3'></td><td></td></tr>
</tbody></table> 
```
then the number of columns it has would be 4. you also couldnt return any selector that would contain 4 `td` cells, since there are no rows in there like that. You could append a hidden row at the end and return that from the getSizingRow function. 

search the issues for how to use getSizingRow, there are plenty of examples.

**Comment by mkoryak** [comment]
I just noticed your fiddle is almost exactly like my example in the docs.

**Comment by smaouad** [comment]
I updated the JsFiddle with  a hidden row in thead 
with 7 empty th. It's should do the trick ?

**Comment by mkoryak** [comment]
you dont need a hidden row. also it doesnt go into the thead, it goes into the tbody. 
you can just select the 2nd row in your table, or put a `grouping` class on the cell with the colspan, and use the exact example from the docs:

http://mkoryak.github.io/floatThead/examples/row-groups/

**Comment by smaouad** [comment]
Thanks for your help i finally get it to work. 
Great Plugin by the way.

**Comment by mkoryak** [comment]
you're welcome
