### ISSUE TITLE
How to update position floatthead?

### ISSUE THREAD

**Issue by tanobi92** [mkoryak/floatThead#318]
I have a table. If I use position: auto/fixed, when I click arrow up button, thead run slowly. If I use position: absolute, thead run not smooth.
How to I use position to have thead run faster and smooth. Help me, please! Thank you.
My example:
https://jsfiddle.net/TaNoBi/4jo4tqf5/3/

**Comment by mkoryak** [comment]
the issue is not with the plugin. your table is so big that the browser takes a few seconds to reflow the table. We can do a hack to make it look better by destroying the plugin before hiding the charts and rebuildint it when done. now it takes longer to do that operation, but it does not look as bad to the user. 

https://jsfiddle.net/4jo4tqf5/5/

i rewrote some of your hiding code to be slightly easier to follow and added a new css selector at the top for it. (you dont need this optimization for the rest of the solution to work)

**Comment by tanobi92** [comment]
Hi @mkoryak , thank you for re-answer.
