### ISSUE TITLE
Header wont align at the correct column when the column order has been changed.

### ISSUE THREAD

**Issue by iArnoldo** [mkoryak/floatThead#324]
So iam changing the table Columns based on a filter in an Select menu. The first change works fine but the second one is a failure: Thead header aligns to the wrong tbody column.

Any Idea how to fix this?

here the [fiddle](https://jsfiddle.net/twvt5tfr/2/)
Cheers
A.

**Comment by mkoryak** [comment]
somewhere in the docs about using it with hidden columns there should have been a mention of `getRowGroups` method which returns row groups belonging to your table when the header is floated. 

You cant just select them from the table because the original header will not be in your table. 

also, you dont need to destroy the plugin and re-create it, you can just trigger `reflow`

https://jsfiddle.net/twvt5tfr/4/
