### ISSUE TITLE
Jumping head in google chrome MacOS

### ISSUE THREAD

**Issue by andreypopov** [mkoryak/floatThead#328]
http://www.giphy.com/gifs/l2Sq18OkeU9YhGCJ2
http://www.giphy.com/gifs/l0HlVxbm3iMoZpSxy

Any table (even demo page).
Google Chrome (FF is ok)
MacOS Sierra

Linux - everything is okay in any browser.

**Comment by mkoryak** [comment]
this is what happens when setting element location in javascript cant keep up with your framerate. There is absolutely nothing I can do about it when the plugin uses `position: 'fixed'` (which is the default for window scrolling).

You can init the plugin with `position:'absolute'` and this will no longer happen:

http://mkoryak.github.io/floatThead/examples/window-scrolling/
