### ISSUE TITLE
floatThead hides fragment targets

### ISSUE THREAD

**Issue by SebastianRose** [mkoryak/floatThead#329]
The floatTheads hide fragment targets.

jsfiddle: https://jsfiddle.net/sj5p74kn/  (sorry, first fiddle - not sure if that helps...)

The table in the jsfiddle is just part of a table, that was generated by the Perl profiler 'Devel::NYTProf' for a very small project.  In real life, those tables tend to be much longer.  That's why I started to use floatThead, which works great in all fairly recent browsers. 

Thanks for that great work!

The only problem are the floatHeaders hiding the table line I want to see.  If you imagine the HTML in the fiddle as http://example.com/xy.html and you klick on a link, that points to http://example.com/xy.html#450 (with a fragment), your supposed to see line 450.  Unfortunately though, that line is hidden behind the floadTheaders.

I added some lines of JavaScript to fix that.  But I feel those lines belong into floatThead.js.

Hope that fiddle helps.  The script there fixes the issue for me.

- browser name/version: any
- OS name: any
- jQuery version: v1.12.4
- floatThead: latest version

PS: Lates 1.x version of jquery is not available on jsfiddle.  Makes more sense to work with local files anyway.   Why not accept HTML attachments?

PPS: Attaching a tar.gz file is not possible here.  I could send you a html file with all scripts and stylesheets as tar.gz, zip or whatever.

**Comment by mkoryak** [comment]
you can link to external resources on jsfiddle, just find the source code and add it as an external resource.

I would rather not work with local files because not everyone wants to put in the time to clean those up and make them easy to consume. I can usually tell pretty quickly what the problem/bug is via jsfiddle. 

I think that adding `$(window).on('hashchange'` listener to the plugin to reflow it might be a good idea.

I couldnt run your fiddle because missing jquery and my script, but I think that the solution you are looking for might look something like this: 

https://jsfiddle.net/sj5p74kn/9/

**Comment by mkoryak** [comment]
if that doesnt work and you want more help, email me at koryak at gmail dot com with your tgz and i can tell a closer look

**Comment by SebastianRose** [comment]
Misha Koryak <notifications@github.com> writes:

> if that doesnt work and you want more help, email me at koryak at gmail dot com with your tgz and i can tell a closer look

Hello Misha,

thanks for the fast reply and the invitation :)


The only problem is, that the table rows with the URL fragment's target
are hidden.

I can live with my workaround.  But if it would work out of the box
would make floatThead.js shine evan a bit more :)


The attachment contains a the HTML file with those looong tables.  The
NYTProf users reach a page like that by clicking on a link with an
URL-fragment that points to a certain table row in the table.  That row
is hidden by the floatTheads.   You'll find my workaround towards the
end of that file.  If you comment it out, you'll see the effect.

There is also a table sorter script in use, which I commented out.  It
does not interfere with floatThead.











-- 
A bus station is where a bus stops. A train station is where a train
stops.
On my desk, I have a work station.... what more can I say...........

                                                       (Bernhard Shaw)

⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽
Sebastian  Rose                                    Software Entwickler
Waldenburger Straße 2
31162 Bad Salzdetfurth

Telefon: 05063 78 14 3 17
Mobil :  0157  75 460 462               E-Mail:  sebastian_rose@gmx.de
⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺

**Comment by mkoryak** [comment]
no email with attachment was received. 

I don't think the code to update scroll position after anchor navigation belongs within floatThead because it only concerns itself with the table header, it does not assume anything about the contents of the tbody and thead for that matter, other than column widths. 

url fragment navigation can happen outside of tables too.

I've been thinking of adding a section of 'recipes' to the docs section where things like this can go. 

After I look at your html, maybe we can find a good clean solution and ill add it there

**Comment by SebastianRose** [comment]
OK. I understand your point.  And I can very well live with that.

So what I need is an advice as how to detect the floating headers container.  I could test for the class `.floatThead-container`, but that's undocumented.   So I believe that could change (coming from the perl corner...).
Hence, I do:
```javascript
        var $table = $tgt.closest('table.floatHeaders');
        // ...
        var fhYPos   = $table.prev().offset().top;   // <- The floating headers - hopefully
```
The last line simply trusts in the fact, that the div.floatThead-container is the previous sibling of the table itself.

**Comment by mkoryak** [comment]
It is documented, in the code - https://github.com/mkoryak/floatThead/blob/master/jquery.floatThead.js#L40

you can use that class if you were explicit about setting it.

**Comment by SebastianRose** [comment]
Thanks. I'll go with
     var fhYPos   = table.prev('.floatThead-container').offset().top;
