### ISSUE TITLE
WAVE accessability tool reports errors on empty TH

### ISSUE THREAD

**Issue by siromega** [mkoryak/floatThead#332]
Using WebAIM's WAVE tool (extension for Google Chrome) to evaluate the accessibility of websites, floatThead is causing an issue because of empty TH. You can replicate this by going to the main product page (http://mkoryak.github.io/floatThead/) and running the WAVE tool. You will see 10 errors, one for each empty TH for each table. Now each of those THs have an aria-description so I think it may not really be an error in the code altering the THEAD, but it is flagged as an error. Maybe don't take out the text in each TH?

Google Chrome, Windows 7.

**Comment by mkoryak** [comment]
I take the text out of the TH because I can't predict how it will be formatted with the user's css. If they have some crazy rules in place that changes the size of the thead, it will break the plugin.

aria-description is the standard for accessibility. I am not going to potentially break the plugin because a tool doesn't think that using a standard is enough.

**Comment by mkoryak** [comment]
There is a workaround. I used to do this text copying thing before (it turned out to be a problem because of css rules issues). If you use release 1.4.2  https://github.com/mkoryak/floatThead/releases

you can use `enableAria` flag to enable this functionality. That flag has been removed in later versions and will not be re-added.
