### ISSUE TITLE
Reflow causes an input inside the header to lose focus

### ISSUE THREAD

**Issue by crbentle** [mkoryak/floatThead#388]
I have a filter input inside of the table header. Any time the window size changes or floatThead('reflow') is called the input loses focus.

jsfiddle: [https://jsfiddle.net/vncfsoen/1/](https://jsfiddle.net/vncfsoen/1/)
Steps to reproduce:
- Make sure the window is short enough so the page has a scroll bar
- Type 'a' in the inner filter to shrink the table below the scroll limit
- Notice that the inner filter input is no longer focused
The same behavior happens if you focus the inner filter and then resize the window.

The outer filter does not lose focus on a reflow.

I have seen this issues on Chrome 60, FF 55, and IE 11.

**Comment by mkoryak** [comment]
In order for this plugin to work it must rip out the header from the DOM, let the browser layout the table to get "optimal" column sizing, then put the header back in. Because the header is removed from the DOM, you lose focus. I make no assumptions about the contents of the header, so I will not restore focus to your input, sorry. Luckily, you should be able to easily do this yourself already. 

If not, take a look at `$table.on('reflowed', function(e, $floatContainer){..}` event in the docs. This is trigged on reflow. 

Another question I have is - why are you triggering reflow in the first place? Why would the height of the table affect the size of the header? have you tried using a different `position` mode?

**Comment by crbentle** [comment]
The input is used to filter table contents. If the original table is longer than the page then the window shows a scroll bar. If the contents are filtered and the scroll bar goes away the table stretches to fit the full page width and the header sizes are not right. I have to reflow to resize the header to match.

I am manually focusing the input using the reflowed event.

`		$('#test-table').floatThead().on('reflowed', function(){
			$('#filter').focus();
		});`

Thanks.
