### ISSUE TITLE
Question: Sticky header inside scroll containers

### ISSUE THREAD

**Issue by mojoaxel** [mkoryak/floatThead#393]
I hope you guys don't mind me opening this issue. I have a rather complex use case where I want to use floatThead. Maybe you can have a look:

https://stackoverflow.com/questions/47710391/sticky-table-header-inside-scrollable-box

_Please feel free to close this issue at any time!_

**Comment by mkoryak** [comment]
Hey, can you please transfer your code into a jsfiddle. I can edit it there and hopefully come up with a solution for you.

**Comment by mojoaxel** [comment]
@mkoryak Cool! I have a jsbin with the example: http://jsbin.com/wuduyez/edit?html,css,js,console,output
Hopefully this helps!

**Comment by mkoryak** [comment]
Ok, this is not supported, the closest thing to what you want that kinda works (but also unsupported) is this:

https://github.com/mkoryak/floatThead/issues/376

The difference between that and your code is that the above code relies on window to do up and down scrolling, and a container to do the side to side. 

you have 2 different containers handling the 2 axis, which I do not support. I tried supporting it once, but it required a lot of code to be rewritten and I do not want to do that because I do not have the same kind of time to support this project that I once had. It works right now for a lot of people.

**Comment by mojoaxel** [comment]
@mkoryak Thanks very much for looking into this! This is very much appreciated! Good look in the future with your project.
