### ISSUE TITLE
How to set dynamically top?

### ISSUE THREAD

**Issue by SergRad** [mkoryak/floatThead#405]
How to set dynamically TOP value when to scroll page up and down
![screenshot_5](https://user-images.githubusercontent.com/6420699/36165650-ee6d2d6a-10f8-11e8-94f4-71be8bb49107.jpg)

- browser Google Chrome. Version 64.0.3282.140 (Official Build) (64-bit)
- OS name - windows 10 (64bit)
- jQuery version v.1.9.1
- floatThead latest

jsfiddle - https://jsfiddle.net/xf1dof15/40/

**Comment by mkoryak** [comment]
You were close. You were missing 2 things:

`top` can take a function 
and  you need to `.trigger('reflow')` when you change the header size to tell floatThead to recalculate things when you change the header height. Otherwise the plugin assumes that the last `top` value should be used. 

https://jsfiddle.net/xf1dof15/42/

**Comment by SergRad** [comment]
Thanks! It's worked!
