### ISSUE TITLE
Blurry theads

### ISSUE THREAD

**Issue by icemall** [mkoryak/floatThead#418]
Plugin makes theads blurry if browser zoom is not default (100%). I'm using Chrome Version 66.0.3359.139 (Official Build) (64-bit).

100%
![image](https://user-images.githubusercontent.com/892639/39468541-2c729e36-4d3c-11e8-83f1-9cd534451f04.png)

90%
![image](https://user-images.githubusercontent.com/892639/39468553-38737336-4d3c-11e8-9427-30494dd2f6c4.png)

110%
![image](https://user-images.githubusercontent.com/892639/39468561-46930508-4d3c-11e8-8241-e7e89176b0ad.png)

P.S. Thanks for the great plugin! :)

**Comment by mkoryak** [comment]
Chrome does not use subpixel anti aliasing when zooming on a transform. It probably a chrome bug.
I cannot detect zoom.

**Comment by mkoryak** [comment]
try forcing this:
https://github.com/mkoryak/floatThead/blob/master/src/jquery.floatThead.js#L843

I am not inclined to make this configurable though, because I hate adding new config options that will affect a very small percentage of users. This one especially sucks because the transform makes the plugin much faster, so disabling it for the 0.001% of users who zoom makes the plugin slower for the remaining 99.9999%.

If you really need this for some reason, you could find a floatThead version where I did not use transforms. Try looking back at the change log to see where I started doing that.

**Comment by mkoryak** [comment]
try this release:

https://cdnjs.com/libraries/floatthead/1.4.2

**Comment by icemall** [comment]
> try forcing this:
> https://github.com/mkoryak/floatThead/blob/master/src/jquery.floatThead.js#L843

Thank you, this solved the issue.
