### ISSUE TITLE
float-container width is not matching with table width

### ISSUE THREAD

**Issue by flexkiran** [mkoryak/floatThead#423]
I am using latest floatThead version 2.1.2 
https://jsfiddle.net/k4kiran/Luayektz/2/

while zooming from 100% to 200% head does not resize to match table width.
It works for initial zoom levels.
![screen shot 2018-07-11 at 4 26 27 pm](https://user-images.githubusercontent.com/3242418/42559843-dcd54f4e-8527-11e8-9691-4da97a7f9d2a.png)

**Comment by mkoryak** [comment]
On mobile, so I haven't looked at it in depth, but I can already tell you
that zooming is not supported because there is no zoom event I can listen
to.

Correct me if I'm wrong

On Jul 11, 2018 4:31 AM, "Kiran Patil" <notifications@github.com> wrote:

I am using latest floatThead version 2.1.2
https://jsfiddle.net/k4kiran/Luayektz/2/

while zooming from 100% to 200% head does not resize to match table width.
[image: screen shot 2018-07-11 at 4 26 27 pm]
<https://user-images.githubusercontent.com/3242418/42559843-dcd54f4e-8527-11e8-9691-4da97a7f9d2a.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mkoryak/floatThead/issues/423>, or mute the thread

**Comment by flexkiran** [comment]
Thanks Misha for quick reply.
Yes I am aware about zoom event not supported.
But it is also not working when I destroy and redraw float header on zoom/resize.

**Comment by mkoryak** [comment]
Ok this is true, but since I cannot detect that zoom is happening, there is
no way I can support it. Things get weird when the page is zoomed. Sorry.
