### ISSUE TITLE
Header in wrong position after JQuery Tab activation, reflow does not fix it

### ISSUE THREAD

**Issue by cabintech** [mkoryak/floatThead#436]
I read some of the issues related to header misplacement after switching tabs, but even using reflow on tab activation does not fix it in my case. Here is a JFiddle example:

[http://jsfiddle.net/6nrymq8o/](http://jsfiddle.net/6nrymq8o/)

Scroll the table down a bit, switch to another tab (e.g. "Sales Reports") and then switch back to the first tab - the header is drawn at the top of the window, detached from the table. In the JS code, reflow is called on tab activation, but the problem remains.

I am using Chrome 74.

**Comment by mkoryak** [comment]
Ah, a jQuery issue with a jsfiddle finally :)

I'll check it out tonight when I get home

**Comment by mkoryak** [comment]
Ok, the problem is that you are expecting to use it like overflow scrolling within a div, but actually you are initializing the plugin as window scrolling (the default). It only appears to work properly - you can break it by scrolling within the table and then scrolling the window.

The fix is simple, tell it about the scrolling container:

http://jsfiddle.net/71mvxtnp/1/

**Comment by cabintech** [comment]
Ah, perfect! That fixed it. Tried a number of other solutions, this is the only one that completely works (now that I understand the container issue). Thanks!
