### ISSUE TITLE
Header never prints using jquery.floatThead

### ISSUE THREAD

**Issue by bchipre** [mkoryak/floatThead#466]
I am trying to fix a fixed header until Navbar where the user can view the table and print the same. So I tried using jquery.floatThead.js which works perfectly w.r.t my requirement in the HTML view window, but when we try to print using this jquery.floatThead, the header (after Preventive Maintenance Calendar for in example) is never printed. 

Where could I going wrong ? or is it an issue with the jquery.floatThead.js script ?
No solution from [Stackoverflow](https://stackoverflow.com/questions/65787502/header-never-prints-using-jquery-floatthead)

Here is a JSFiddle : https://jsfiddle.net/ja8xhn63/1/

**Comment by mkoryak** [comment]
I see that you print the table by ripping out it's html and opening a new
window with it, which you print.

For this to work correctly with the pluggin, I suggest that you first
destroy it before you copy it's html. Then after you copy the html you can
recreate the pluggin again.

Look for the destroy method in the docs.

This issue is happening because the pluggin modifies your table html while
it is active. This modification is transparent to you, the user, but your
table is actually 2 tables perfectly positioned to look like the original.
The pluggin supports printing, but only if you print the page where it is
running. When you copy the outerHtml, you take the page structure but not
the active javascript.

**Comment by bchipre** [comment]
That worked perfectly. Just made this change 
`var myApp = new function() {
    this.printTable = function() {
    var reinit = $('table').floatThead('destroy');`
and while printing is done added
`win.print();
      win.close();
      reinit();`

That worked like a charm. Thankx @mkoryak
