### ISSUE TITLE
Fix Multiple THEAD in one single Table

### ISSUE THREAD

**Issue by felipeleite** [mkoryak/floatThead#479]
Please include the following:
- description of the issue and steps to reproduce
- jsfiddle that reproduces your issue in its simplest form possible [required]

In fact is more like a question. Is there a way to fix the header of a table with multiples thead tag?
Thanks in advance.
![image](https://github.com/mkoryak/floatThead/assets/3638689/2eeffce6-daab-4489-8712-820f8a7d6b90)

no jsfiddle == your issue will be closed

**Comment by mkoryak** [comment]
No

**Comment by mkoryak** [comment]
It is possible to write some code that makes that work though.

https://jsfiddle.net/od6wt5as/1/

One important detail here: I select everything I need inside the able **before** running `floatThead` because it will modify the DOM of the table and put the thead outside of the table. If you select it first, you can work with the references without having to worry about where it is. 

I did a bad thing here and cloned some elements. I had to do that because I dont want to move them from the next thead so it can have a height. You can ensure the height by setting it on the element if the cloning is a problem. 

Hopefully that gives you an idea of how to proceed if you decide to still use this crappy plugin.

**Comment by mkoryak** [comment]
You're welcome.
