### ISSUE TITLE
Browser Zooming Issue

### ISSUE THREAD

**Issue by Sriram143** [mkoryak/floatThead#48]
Hi,

i Have a Big Table it contains 50 columns now i am changing the browser zoom level to 33% the headers alignment is messed up. in the last column header is partly visible..

**Comment by stephenmcd1** [comment]
I'm running into problems when I use CSS to zoom my page (interestingly enough, I haven't had any problems when the user manually zooms in the browser).  We have a page that everybody always zooms in (it is displayed on a large projector and small text is hard to read from across the room).  I wanted to provide 'automatic' zoom and added:  body {zoom: 175%} to my CSS.  That seemed to do the trick however I ran into some issues with this library.

By throwing in some extra 'reflow' calls, I can get things almost perfect.  There is one remaining issue that if I scroll down on the page, the header will scroll away (off the top of the page) when I'm only about 80% down the table.  I've found that if I reflow on scroll, that fixes it....so I have various workarounds (basically spamming reflow) but it would be nice if zoom was natively supported.

**Comment by mkoryak** [comment]
zoom isnt supported because I dont know of any way to automatically detect it in a non-expensive way. 

you are the first person with this problem in 2 years, so even if a fix existed, I am not sure it would be worth it to add to code - if it will be a feature used by 1 person.

I can take a look at what you have, maybe we can find some middle ground, or a better workaround than what you got. can you put the code up somewhere, jsfiddle perhaps?

**Comment by stephenmcd1** [comment]
I would be fine if my code was responsible for communicating the zoom level to your library.  In my case, I know the zoom level and I know whenever I happen to change the zoom level programmatically and I would have no problems if I had to make a call to floatThead('reflow') or something and pass in the current zoom level.  Perhaps that moves the annoying burden of knowing the zoom level to the consumers so your logic doesn't need to do something that may not be practical to do generically?

I totally understand this could be an obscure feature request.  If it 'doesn't make the cut', I would be fine with that.  It seems there are a lot of things that I use which don't play nicely with zooming so floatThead wouldn't be the first.

I stole the example from [this page](http://mkoryak.github.io/floatThead/examples/window-scrolling/) and made it into a fiddle with simple CSS to control the zoom.  It should be obvious some of the oddities that result.  See: https://jsfiddle.net/spcuhbeb/

Thanks for looking into it!

**Comment by stephenmcd1** [comment]
Actually, I was probably too hasty in my jsfiddle.  Here is a much better one that behaves much better (only a few minor issues) and is more like my application:  https://jsfiddle.net/stephenmcd1/spcuhbeb/1/

**Comment by mkoryak** [comment]
thanks for putting in an effort  here, ill see what I can do with it today.

**Comment by mkoryak** [comment]
sorry, havent had time to look at this.

**Comment by mkoryak** [comment]
still on my radar, been really busy.

**Comment by mkoryak** [comment]
hmm, I thought that I would just need to multiple the computed table height by the zoom, but that does not appear to the the case.

**Comment by stephenmcd1** [comment]
@mkoryak Thanks for keeping me updated.  This is certainly not a critical issue for me so as long as it is on your radar, I'm happy.  Good luck! :-)

**Comment by mkoryak** [comment]
It is not looking good. there is absolutely no correlation between the table height that the browser reports and the zoom level. see:

https://jsfiddle.net/spcuhbeb/2/

I thought that maybe it would be multiple, but it is not. 
If you can find a way to figure out the "real" table height at different zoom levels, then we can talk

**Comment by mkoryak** [comment]
I poked more, and couldnt find any way to get any useful height information from the browser. I am going to close this as wontfix, but if you can find a solution that works for getting height in this fiddle https://jsfiddle.net/spcuhbeb/2/ then please reopen

**Comment by stephenmcd1** [comment]
That is pretty odd behavior.  However, it seems the browser is just giving you the 'unzoomed' height.  I've updated your fiddle to multiple the outerHeight() value by the zoom level and then you'll see more reasonable values.  See here:  https://jsfiddle.net/stephenmcd1/spcuhbeb/3/.

I've made a more comprehensive fiddle that shows that multiplying the 'raw' height by the zoom level gives very accurate results.  It can sometimes be off a pixel or two but that's barely noticeable.  See: http://jsfiddle.net/stephenmcd1/swu5s4Lx/.

Of course, this comes back to your original problem of knowing the zoom level.  In my case, I'm more than happy supplying your library with the zoom level because I'll know what the zoom level is.
