### ISSUE TITLE
Misalign columns on IE11

### ISSUE THREAD

**Issue by mlorant** [mkoryak/floatThead#79]
When I'm using the `floatThread` plugin on IE11 (with Django admin default template), the header row is misaligned compared to the table.

An image is worth a thousand words: 

![ie11-bug-misalign-columns png](https://cloud.githubusercontent.com/assets/532337/2794905/cc6dbf9e-cbf2-11e3-8744-df38eaf05989.jpg)

This doesn't happen on Firefox and Chrome. You can find [the HTML template there](https://github.com/django/django/blob/master/django/contrib/admin/templates/admin/change_list_results.html) (line 9 to end) and [the CSS here](https://github.com/django/django/blob/master/django/contrib/admin/static/admin/css/changelists.css) (the table is in a `div#changelist`, so first rules are also applied to the table)

**Comment by nghingothanhnghi** [comment]
Helo master,
i also have problem for responsive table in bootstrap. It's running with horizontal scrollbar and vertical scroll in the container. Thead and tbody not matched together. I don't known why, only on IE. There is my fiddle
https://jsfiddle.net/#&togetherjs=zuCzwvAE7r

**Comment by mkoryak** [comment]
Hi,
Your fiddle links to a some collab thing. I want the code.

Also, have you read the docs about how to use this plugin with IE? I think there even a link to that form the readme.

Without the code, I cant help you

**Comment by mkoryak** [comment]
please make a new issue @nghingothanhnghi 
I am closing this one because every IE related issue is ending up in here

**Comment by mkoryak** [comment]
actually, this is already closed. ha. please make a new issue

**Comment by nghingothanhnghi** [comment]
Sorry mkoryak,You're kindly, i'll update code on fiddle soon, hoping you can help me with this issue from table                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Misha KoryakSent: 22:01 Thứ ba, ngày 27 tháng sáu năm 2017To: mkoryak/floatTheadReply To: mkoryak/floatTheadCc: Nghị; CommentSubject: Re: [mkoryak/floatThead] Misalign columns on IE11 (#79)Hi,
Your fiddle links to a some collab thing. I want the code.
Also, have you read the docs about how to use this plugin with IE? I think there even a link to that form the readme.
Without the code, I cant help you

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mkoryak/floatThead","title":"mkoryak/floatThead","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mkoryak/floatThead"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mkoryak in #79: Hi,\r\nYour fiddle links to a some collab thing. I want the code.\r\n\r\nAlso, have you read the docs about how to use this plugin with IE? I think there even a link to that form the readme.\r\n\r\nWithout the code, I cant help you\r\n"}],"action":{"name":"View Issue","url":"https://github.com/mkoryak/floatThead/issues/79#issuecomment-311386462"}}}

**Comment by nghingothanhnghi** [comment]
OK, thanks you so much, i'll close. And make. 1 new issue                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Misha KoryakSent: 22:04 Thứ ba, ngày 27 tháng sáu năm 2017To: mkoryak/floatTheadReply To: mkoryak/floatTheadCc: Nghị; MentionSubject: Re: [mkoryak/floatThead] Misalign columns on IE11 (#79)actually, this is already closed. ha. please make a new issue

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mkoryak/floatThead","title":"mkoryak/floatThead","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mkoryak/floatThead"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mkoryak in #79: actually, this is already closed. ha. please make a new issue"}],"action":{"name":"View Issue","url":"https://github.com/mkoryak/floatThead/issues/79#issuecomment-311387210"}}}
